---
title: "COVID 19 - some simple data visualizations for US data"
output: 
  rmdformats::readthedown:
    highlight: tango 
    df_print: kable
    fig_width: 20
    fig_height: 15
    self_contained: no
---
<style type="text/css">
.main-container {
  max-width: 1500px !important;
  margin-left: auto;
  margin-right: auto;
}
</style>


Some other covid19 visualizations:

https://coronavirus.1point3acres.com/

https://coronavirus.jhu.edu/map.html


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(kableExtra)
library(tidyverse)
library(ggthemes)
library(extrafont)
library(rmdformats)
```

```{r, include=FALSE}

# theme settings 

DOT_SIZE <- 2
DOT_SIZE_SMALL <- 1
DOT_SIZE_LARGE <- 3
LINE_SIZE_LIGHT <- 0.15
LINE_SIZE_MID <- 0.2
LINE_SIZE <- 0.5
LINE_SIZE_WIDE <- 1
FONT_SIZE_SMALL <- 5
FONT_SIZE <- 6
FONT_SIZE_MID <- 7
FONT_SIZE_BIG <- 12
BCKGDCOLOR <- "#FFFFFF"
TEXTCOLOR <- "#444444"
LINE_COLOR <- "#444444"
LINE_COLOR_LIGHT <- "#dddddd"


PALETTE <- c("#6298f5", "#ed80ae", "#faa970", "#71bf76", "#999999") 
TABEALU20 <- c("#4E79A7", "#A0CBE8", "#F28E2B", "#FFBE7D", "#59A14F",
"#8CF17D", "#B6992D", "#EDC948", "#499894", "#76B7B2",
"#E15759", "#FF9D9A", "#79706E", "#BAB0AC", "#D37295",
"#FABFD2", "#B07AA1", "#D4A6C8", "#9D7660", "#D7B5A6")

DIFF_COLOR <- "#877991"
GOLDEN_COLOR <- "#e8bb3f"
GRAY_COLOR1 <- "#888888"
GRAY_COLOR2 <- "#aaaaaa"
ORANGE <- MEAN_COLOR1 <- "#F28E2B"
BLUE <- RANGE_COLOR1  <- "#1f77b4"
MEAN_COLOR2 <- "#EDC948"
RANGE_COLOR2 <- "#76B7B2"
DIFF_COLOR2 <- "#D37295"

this_PALETTE <- c(BLUE, ORANGE)

my_theme <- theme(
                                      #line,
                                      #rect,
                                      #text,
  title = element_text(size = FONT_SIZE_BIG, colour = TEXTCOLOR, face = "bold", family = "Avenir", vjust = 1, hjust = 0.5), 
                                      #aspect.ratio,
  axis.title.x = element_text(size = FONT_SIZE, colour = TEXTCOLOR, face = "bold", family = "Avenir", vjust = 0.5), 
  axis.title.y = element_text(size = FONT_SIZE,  colour = TEXTCOLOR, angle = 90, face = "bold", family = "Avenir", vjust = 0.5), 
                                      #?axis.title.x.top,
                                      #?axis.title.x.bottom,
  axis.text = element_text(size = FONT_SIZE,  colour = TEXTCOLOR, face = "plain", family = "Avenir"), 
                                      #?axis.title.y.left,
                                      #?axis.title.y.right,
  axis.text.x = element_text(size = FONT_SIZE_SMALL,  colour = TEXTCOLOR, face = "plain", family = "Avenir", angle = 90, vjust = 0.5, hjust=1), 
                                      #?axis.text.x.top,
                                      #?axis.text.x.bottom,
  #axis.text.y,
                                      #?axis.text.y.left,
                                      #?axis.text.y.right,
  axis.ticks = element_line(colour = LINE_COLOR, size = LINE_SIZE_LIGHT, linetype = "solid"),
  #axis.ticks.x,
                                      #?axis.ticks.x.top,
                                      #?axis.ticks.x.bottom,
  #axis.ticks.y,
                                      #?axis.ticks.y.left,
                                      #?axis.ticks.y.right,
  axis.ticks.length = unit(.1, "lines"),
  #axis.ticks.length.x,
                                      #?axis.ticks.length.x.top,
                                      #?axis.ticks.length.x.bottom,
  #axis.ticks.length.y,
                                      #?axis.ticks.length.y.left,
                                      #?axis.ticks.length.y.right,
  axis.line = element_line(colour = LINE_COLOR, size = LINE_SIZE_LIGHT, linetype = "solid"),
  #axis.line.x,
                                      #?axis.line.x.top,
                                      #?axis.line.x.bottom,
  #axis.line.y,
                                      #?axis.line.y.left,
                                      #?axis.line.y.right,
  legend.background = element_blank(),
  legend.margin = margin(.1, .1, .1, .1),
  legend.spacing = unit(0.5, "lines"),
                                      #?legend.spacing.x,
                                      #?legend.spacing.y,
  legend.key = element_blank(),
  legend.key.size = unit(1, "lines"),
  #legend.key.height,
  #legend.key.width,
  legend.text = element_text(size = FONT_SIZE_SMALL,  colour = TEXTCOLOR, face = "plain", family = "Avenir"),
  legend.text.align = 0,#left
  legend.title = element_text(size = FONT_SIZE_SMALL, colour = TEXTCOLOR, face = "plain", family = "Avenir"),
  legend.title.align = 0,#left
  legend.position = "left",
  #legend.direction, #auto
  legend.justification = "left",
  #legend.box = element_rect(fill = NA, colour = LINE_COLOR, size = 0.1), #auto
  legend.box.just = "left", # because of bottom
  legend.box.margin = margin(1, 1, 1, 1),
  legend.box.background = element_blank(),
  legend.box.spacing = unit(1, "lines"),
  panel.background = element_blank(),
  panel.border = element_blank(),
  panel.spacing = unit(1, "lines"),
  #panel.spacing.x,
  #panel.spacing.y,
  #panel.grid,
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.grid.major.y = element_line(colour = LINE_COLOR, size = LINE_SIZE_MID, linetype = "dotted"),
  #panel.grid.major.y,
  #panel.grid.minor.x,
  #panel.grid.minor.y, 
  panel.ontop = TRUE,
  plot.background = element_blank(),
  plot.title  = element_text(size = FONT_SIZE_BIG,  colour = TEXTCOLOR, face = "plain", family = "Avenir", vjust = 1),
  #?plot.title.position,
  #plot.subtitle,
  plot.caption = element_text(size = FONT_SIZE_BIG,  colour = TEXTCOLOR, face = "plain", family = "Avenir"),
  #?plot.caption.position,
  #?plot.tag,
  plot.tag.position = "top",
  plot.margin = margin(10, 10, 10, 10),
  strip.background = element_blank(),
  #strip.background.x,
  #strip.background.y,
  strip.placement = "outside",
  strip.text = element_text(size = FONT_SIZE_BIG,  colour = TEXTCOLOR, face = "plain", family = "Avenir"),
  #strip.text.x,
  #strip.text.y,
  #strip.switch.pad.grid,
  #strip.switch.pad.wrap,
  complete = FALSE,
  validate = TRUE
)

theme_set(my_theme)
```

```{r}

# data source https://www.census.gov/data/datasets/time-series/demo/popest/2010s-state-total.html and wikipedia
df_population <- data.frame(
  state = c("AK", "AL", "AR", "AS", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", 
            "GA", "GU", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", 
            "MD", "ME", "MI", "MN", "MO", "MP", "MS", "MT", "NC", "ND", "NE", 
            "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "PR", "RI", 
            "SC", "SD", "TN", "TX", "UT", "VA", "VI", "VT", "WA", "WI", "WV", "WY"),
  population = c(731545, 4903185, 3017804, 55465 , 7278717, 39512223, 5758736, 3565287, 705749, 973764, 21477737,
                 10617423, 165768, 1415872, 3155070, 1787065, 12671821, 6732219, 2913314, 4467673, 4648794, 6892503, 
                 6045680, 1344212,  9986857, 5639632, 6137428, 56882, 2976149, 1068778, 10488084, 762062, 1934408,
                 1359711, 8882190, 2096829, 3080156, 19453561, 11689100, 3956971, 4217737, 12801989, 3193694, 1059361,
                 5148714, 884659, 6829174, 28995881, 3205958, 8535519, 106977 , 623989, 7614893, 5822434, 1792147, 578759)
)

# The Atlantic Monthly Group (CC BY-NC 4.0)
# source: https://covidtracking.com/api

df_daily <- fread("https://covidtracking.com/api/v1/us/daily.csv")
df_states <- fread("https://covidtracking.com/api/v1/states/daily.csv") %>% 
               replace(is.na(.), 0) %>%
               inner_join(df_population, by = "state")%>%
               mutate(date = as.Date(as.character(date), "%Y%m%d"))

tableau10 <- as.list(ggthemes_data[["tableau"]][["color-palettes"]][["regular"]][[1]][,2])$value
first_day <- as.Date("2020-03-15") # to select a dat
today <-  as.Date(toString(max(df_states$date)))
  
kable(head(df_states, n = 3))
```

## Rhode Island (as I live in RI now)
```{r fig.height = 8, fig.width = 10, warning=FALSE,  message=FALSE}
df_states %>% filter(state == "RI") %>%
    ggplot() %>%
    + geom_label(x = first_day, y = 850, color = "darkgray", label = "total positive", size = 2, hjust = 0) %>%
    + geom_text(mapping = aes(x = date, y = 950, label = positive), color = "darkgray", size = 2, angle = 90, hjust = 0) %>%
    + geom_label(x = first_day, y = 800, color = "black", label = "death", size = 2, hjust = 0) %>%
    + geom_label(x = first_day, y = 750, color = tableau10[2], label = "positiveIncrease", size = 2, hjust = 0) %>%
    + geom_label(x = first_day, y = 700, color = tableau10[1], label = "hospitalizedCurrently", size = 2, hjust = 0) %>%
    + geom_line(mapping = aes(x = date, y = death), alpha = 0.7, color = "black", size = LINE_SIZE) %>%
    + geom_text(mapping = aes(x = date - 0.5, y = death + 10, label = death), color = "black", size = 1.5) %>%
    + geom_point(mapping = aes(x = date, y = death), color = "black", shape = 10) %>%
    + geom_line(mapping = aes(x = date, y = hospitalizedCurrently), alpha = 0.7, color = tableau10[1], size = LINE_SIZE) %>%
    + geom_text(mapping = aes(x = date - 0.5, y = hospitalizedCurrently + 10, label = hospitalizedCurrently), color =  tableau10[1], size = 1.5) %>%
    + geom_point(mapping = aes(x = date, y = hospitalizedCurrently), color = tableau10[1], shape = 15) %>%
    + geom_line(mapping = aes(x = date, y = positiveIncrease), alpha = 0.7, color = tableau10[2], size = LINE_SIZE) %>%
    + geom_text(mapping = aes(x = date - 0.5, y = positiveIncrease + 10, label = positiveIncrease), color =  tableau10[2], size = 1.5) %>%
    + geom_point(mapping = aes(x = date, y = positiveIncrease), color = tableau10[2]) %>%
    + scale_x_date(limits = c(first_day, today), breaks = seq(first_day, today, by = "day")) %>%
    + xlab("Date") + ylab("") + ggtitle("RI")


```



## US - all states
```{r fig.height = 6, fig.width=10, warning=FALSE,  message=FALSE}


df_states %>% group_by(date) %>%
    summarise(positiveIncrease = sum(positiveIncrease), hospitalizedCurrently = sum(hospitalizedCurrently), total = sum(positive)) %>% 
    ungroup() %>%
    ggplot() %>%
    + geom_label(x = first_day, y = 60000, color = "darkgray", label = "total positive: ", size = 2, hjust = 0) %>%
    + geom_text(mapping = aes(x = date, y = 63000, label = total), color = "darkgray", size = 2, angle = 90, hjust = 0) %>%
    + geom_label(x = first_day, y = 50000, color = tableau10[1], label = "hospitalizedCurrently", size = 2, hjust = 0) %>%
    + geom_label(x = first_day, y = 55000, color = tableau10[2], label = "positiveIncrease", size = 2, hjust = 0) %>%
    + geom_line(mapping = aes(x = date, y = hospitalizedCurrently), alpha = 0.7, color = tableau10[1], size = LINE_SIZE) %>%
    + geom_text(mapping = aes(x = date - 0.5, y = hospitalizedCurrently + 1000, label = hospitalizedCurrently), color =  tableau10[1], size = 1.5) %>%
    + geom_point(mapping = aes(x = date, y = hospitalizedCurrently), color = tableau10[1], shape = 15) %>%
    + geom_line(mapping = aes(x = date, y = positiveIncrease), alpha = 0.7, color = tableau10[2], size = LINE_SIZE) %>%
    + geom_text(mapping = aes(x = date - 0.5, y = positiveIncrease + 1000, label = positiveIncrease), color =  tableau10[2], size = 1.5) %>%
    + geom_point(mapping = aes(x = date, y = positiveIncrease), color = tableau10[2]) %>%
    + scale_x_date(limits = c(first_day, today), breaks = seq(first_day, today, by = "day")) %>%
    + xlab("Date") + ylab("") + ggtitle("US - positiveIncrease & hospitalizedCurrently")



```


##  US - positiveIncrease by state
```{r fig.height=20, fig.width = 15, warning=FALSE,  message=FALSE}

num_lag <- 21

find_coef <- function(x, y){
  m <- lm(y ~ x)
  return(coef(m)[2])
}


df_colors <-  df_states %>%
  group_by(state)%>%
  arrange(date, .by_group = TRUE) %>%
  slice_tail(n = num_lag) %>% # last N days
  summarise(trend_coef = find_coef(date, positiveIncrease)) %>% 
  mutate(trend_color = ifelse(trend_coef > 0, "increasing", ifelse(trend_coef < 0, "decreasing", "stable"))) %>% 
  ungroup()%>%
  replace(is.na(.), 0) %>%
  select(state, trend_coef, trend_color) 
 
  
df_states %>% 
    inner_join(df_colors, by = "state") %>%
    ggplot() %>%
    + geom_smooth(mapping = aes(x = date, y = positiveIncrease), color = "gray", alpha = 0.3, method = "loess", size = LINE_SIZE) %>%
    + geom_line(mapping = aes(x = date, y = positiveIncrease, color = trend_color), alpha = 0.7, size = LINE_SIZE) %>%
    + geom_point(mapping = aes(x = date, y = positiveIncrease, color = trend_color), size = 1) %>%
        + scale_x_date(limits = c(first_day, today), breaks = seq(first_day, today, by = "week")) %>%
    + scale_colour_tableau() %>%
    + facet_wrap(state ~ ., ncol = 6, scales = "free")  %>%
    + xlab("Date") + ylab("") + ggtitle("US - positiveIncrease by state, colored by trend of last 21 days")
```


##  US - hospitalizedCurrently by state
```{r fig.height=20, fig.width = 15, warning=FALSE,  message=FALSE}

df_states %>% 
    ggplot() %>%
    + geom_smooth(mapping = aes(x = date, y = hospitalizedCurrently), color = "gray", alpha = 0.3, method = "loess", size = LINE_SIZE) %>%
    + geom_line(mapping = aes(x = date, y = hospitalizedCurrently), alpha = 0.7, color = tableau10[1], size = LINE_SIZE) %>%
    + geom_point(mapping = aes(x = date, y = hospitalizedCurrently), color = tableau10[1], size = 1) %>%
    + scale_x_date(limits = c(first_day, today), breaks = seq(first_day, today, by = "week")) %>%
    + facet_wrap(state ~ ., ncol = 6, scales = "free")  %>%
    + xlab("Date") + ylab("") + ggtitle("US - hospitalizedCurrently by state")
```



## US - testPositiveRate against testedPopulationRate

```{r fig.height=20, fig.width = 15, warning=FALSE,  message=FALSE}
df_states %>% 
    mutate(testPositiveRate = positiveIncrease / totalTestResultsIncrease, testedPopulationRate = totalTestResults / population) %>%
    ggplot() %>%
    + geom_smooth(mapping = aes(x = testedPopulationRate, y = testPositiveRate), color = "gray", alpha = 0.3, method = "loess", size = LINE_SIZE) %>%
    + geom_line(mapping = aes(x = testedPopulationRate, y = testPositiveRate), alpha = 0.7, color = tableau10[4], size = LINE_SIZE) %>%
    + geom_point(mapping = aes(x = testedPopulationRate, y = testPositiveRate), color = tableau10[4], size = 1) %>%
    + scale_x_continuous(limits = c(0, 0.20), breaks = seq(0, 1, by = 0.01)) %>%
    + scale_y_continuous(limits = c(-.25, 1.25), breaks = seq(0, 1, by = 0.2)) %>%
    + facet_wrap(state ~ ., ncol = 6, scales = "free")  %>%
    + xlab("testPositiveRate") + ylab("testedPopulationRate") + ggtitle("US - testPositiveRate against testedPopulationRate")
```

## US - death per 10k by state
```{r fig.height=20, fig.width = 15, warning=FALSE,  message=FALSE}
df_states %>% 
    mutate(deathPer10K = death / population * 10000) %>%
    ggplot() %>%
    + geom_line(mapping = aes(x = date, y = deathPer10K), alpha = 0.7, color = tableau10[3], size = LINE_SIZE) %>%
    + geom_point(mapping = aes(x = date, y = deathPer10K), color = tableau10[3], size = 1) %>%
    + scale_x_date(limits = c(first_day, today), breaks = seq(first_day, today, by = "week")) %>%
    + scale_y_continuous(limits = c(0, 20), breaks = seq(0, 20, by = 5)) %>%
    + facet_wrap(state ~ ., ncol = 6, scales = "free")  %>%
    + xlab("date") + ylab("death per 10k") + ggtitle("US - death per 10k by state")
```


## US - positive per 1k by state
```{r fig.height=20, fig.width = 15, warning=FALSE,  message=FALSE}
df_states %>% 
    mutate(positivePerOneK = positive / population * 1000) %>%
    ggplot() %>%
    + geom_line(mapping = aes(x = date, y = positivePerOneK), alpha = 0.7, color = tableau10[4], size = LINE_SIZE) %>%
    + geom_point(mapping = aes(x = date, y = positivePerOneK), color = tableau10[4], size = 1) %>%
    + scale_y_continuous(limits = c(0, 25), breaks = seq(0, 25, by = 5)) %>%
    + scale_x_date(limits = c(first_day, today), breaks = seq(first_day, today, by = "week")) %>%
    + facet_wrap(state ~ ., ncol = 6, scales = "free")  %>%
    + xlab("date") + ylab("") + ggtitle("US - positivePerOneK by state")
```


## US - tested amount by state
```{r fig.height=20, fig.width = 15, warning=FALSE,  message=FALSE}
df_states %>% 
    mutate(testResultsIncrease = positiveIncrease + negativeIncrease) %>%
    ggplot() %>%
    + geom_smooth(mapping = aes(x = date, y = testResultsIncrease), color = "gray", alpha = 0.3, method = "loess", size = LINE_SIZE) %>%
    + geom_line(mapping = aes(x = date, y = testResultsIncrease), alpha = 0.7, color = tableau10[7], size = LINE_SIZE) %>%
    + geom_point(mapping = aes(x = date, y = testResultsIncrease), color = tableau10[7], size = 1) %>%
    + scale_x_date(limits = c(first_day, today), breaks = seq(first_day, today, by = "week")) %>%
    + facet_wrap(state ~ ., ncol = 6, scales = "free")  %>%
    + xlab("date") + ylab("testResultsIncrease") + ggtitle("US - testResultsIncrease by state")
```
